site_name: Movie Recommendation System Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - API Documentation:
    - Overview: api/overview.md
    - Deployment: api/deployment.md
    - Endpoints: api/endpoints.md
  - Frontend Documentation:
    - Overview: frontend.md
  - Database:
    - Schema: db/schema.md
    - Setup: db/setup.md
  - Model:
    - Training: model/training.md
    - Deployment: model/deployment.md
  - Data Visualization:
    - Overview: data-viz/overview.md
    - Movies: data-viz/movies.md
    - Users: data-viz/users.md
    - Ratings: data-viz/ratings.md
  - Development:
    - Setup: development/setup.md
    - Guidelines: development/guidelines.md
  - Code:
    - Model Implementation: code/model_implementation.md
    - Data Processing: code/data_processing.md
    - Running the Model: code/running_model.md
    - Running on Google Colab: code/running_on_colab.md
    - Colab Training Guide: code/colab_guide.md
  - Data:
    - Data Collection: data/collection.md
    - Data Processing: data/processing.md
    - Data Analysis: data/analysis.md
  - API:
    - Authentication: api/authentication.md
  - Deployment:
    - Overview: deployment/overview.md
    - Requirements: deployment/requirements.md
    - Configuration: deployment/configuration.md
    - Monitoring: deployment/monitoring.md
    - Google Cloud Run: deployment/google_cloud_run.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes

repo_url: https://github.com/yourusername/movie_recommendation
repo_name: movie_recommendation 